# Generated by Django 3.2.5 on 2022-09-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stamp',
            name='is_challenge',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
