# Generated by Django 3.2.5 on 2022-09-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamp', '0002_stamp_is_challenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stamp',
            name='is_challenge',
            field=models.IntegerField(default=0),
        ),
    ]
